### ISSUE TITLE
Issue replacing LaunchWrapper?

### ISSUE THREAD

**Issue by hadn69** [DimensionalDevelopment/VanillaFix#114]
I'm having a crash on startup with the latest dev build. I'm not sure if its a config problem on my end or an actual bug. log: https://gist.github.com/hadn69/2be62a7fa68dd3a6b2e30c54ad046cba

**Comment by Rongmario** [comment]
Don't use the dev version if you don't know how it works.
MultiMC isn't yet supported.

**Comment by hadn69** [comment]
Where was the mention that MultiMC isn't yet supported at?

**Comment by Rongmario** [comment]
Everywhere. That's why you shouldn't use dev builds, because you are incoherent.

**Comment by tterrag1098** [comment]
Everywhere being...where? Is it actually written down or are you just being an asshole for no reason?

**Comment by ScarletWolf275** [comment]
> Everywhere being on discord and reddit.

Except GitHub is where that dev build is hosted isn't it?
And it says nowhere on GitHub. All there is is that sad excuse for a README.md

**Comment by Rongmario** [comment]
And again the dev build isn't for anyone to use right now.

**Comment by ScarletWolf275** [comment]
That doesn't automatically give you the right to shout at people for trying it. To me, you just seem that you want to be angry at life and all of existence because none of the things that happen in the universe go your way. Hadn was trying a public dev build, one that is put on what's basically a code sharing platform, one where the code is open source and you can do whatever you want with it even if you are a 9 year old messing about on the internet. It isn't anyone's burden to get mad for someone trying something intended for trying publicly. It's like you put up a lemonade stand but shout at people for lining up because the lemons are not fully squeezed yet.

**Comment by Rongmario** [comment]
Sigh. No one shouted, don't be triggered.

Drama stirrers.

**Comment by ScarletWolf275** [comment]
I'm sorry for being overly realistic, replace "shout at people" with "be an asshole to".
And I stand corrected, you don't want to be angry at life, you ARE already angry at life.

**Comment by Agrax** [comment]
You CAN try it. Rongy doesn’t say it’s forbidden. He just says you can’t cry if you have issues when trying to launch a DEV build, which is directed only for devs

**Comment by Rongmario** [comment]
No one is angry at life, you all are for some reason.

**Comment by ScarletWolf275** [comment]
You CAN look at the issue and help, but you don't have to look and be an asshole when someone provides a genuine question to be answered.

**Comment by Rongmario** [comment]
Already helped. End of.

**Comment by ScarletWolf275** [comment]
> Everywhere. That's why you shouldn't use dev builds, because you are incoherent.

If you see that as helping and not releasing your anger on an anonymous comment, then you are one human with a truly clouded mentality. There's none other incoherent here but you because you expect people to go all over the place searching for info about a dev build on Discord & Reddit, where said dev build is not hosted on Discord & Reddit. You just can't be helped, you're not worth arguing with anymore, those are 20-ish minutes of my life I will never be getting back.

**Comment by Rongmario** [comment]
There contains no anger. I don't expect anyone to search anywhere. The build isn't meant for anyone without insight or to an average player.

Thanks for wasting my time.

**Comment by Runemoro** [comment]
Fixed
