### ISSUE TITLE
Failure to keep game stable

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [DimensionalDevelopment/VanillaFix#116]
Whenever the game "Crashes" and shows the crash report with the possible causes, clicking the "return to title menu" button, then attempting to re-join a server just makes the game hang.

No crash reports as it never crashes, just hangs and never goes anywhere.

Have had to remove this mod due to this issue.
This mod is having issues in the Foolcraft 3 Modpack (Unmodified from the download link provided on their page)

**Comment by Rongmario** [comment]
Please can you attach a log below?

**Comment by Runemoro** [comment]
Does this happen with all crashes (even F3 + C), or just crashes from a certain mod?

**Comment by Revvilo** [comment]
Yes, it happens with F3+C.

From testing, it's Custom Main Menu.
Easy to reproduce, too, since with only 2 mods the game runs like a dream.
At the time of posting it affects the latest Forge, VF and CMM.
- Make new world
- F3+C it
- Try log back in
- Stops loading at that "0%" screen that I've never actually seen do anything useful

Here are the latest versions I was able to reproduce it on, for future reference;

| Mod | Version |
|-|-|
| Forge | 14.23.4.2760 |
| Custom Main Menu| MC1.12.2-2.0.8 |
| Vanillafix | 1.0.9-97 |

I hope this helps :)

**Comment by Runemoro** [comment]
Duplicate of #90 , this has been fixed in the dev build (next curseforge version).

**Comment by ZombieHDGaming** [comment]
Just so this does not happen with other packs and such, I will post a build this weekend with any current commits besides our major performance overhaul code as a sort of mini release and to get some fixes out there for new and current issues.
