### ISSUE TITLE
Mod not working on server

### ISSUE THREAD

**Issue by Jacky10X** [DimensionalDevelopment/VanillaFix#15]
Minecraft version:1.12.2
Mod version: VanillaFix-1.0.2-18.jar
crash log:
https://pastebin.com/JKTc7XKY

**Comment by Jacky10X** [comment]
you mean this?
https://pastebin.com/TrZCQDJq

**Comment by ZombieHDGaming** [comment]
Yes, I noticed that now. There is currently a bug in our code with our ModIdentification class trying to access those classes, which we already know of and are trying to fix. I'd recommend removing VanillaFix or going back to the CurseForge release until we can fix that issue, since it likes to crash servers for some reason. It should hopefully be fixed within the next few days or so.

**Comment by Runemoro** [comment]
Fixed.
