### ISSUE TITLE
HasteBin --> PrivateBin

### ISSUE THREAD

**Issue by Eddi2015** [DimensionalDevelopment/VanillaFix#4]
Maybe switch from HasteBin to PrivateBin ( https://privatebin.info/ ) cuz it uses de/encryption and seems to be more secure.

**Comment by Runemoro** [comment]
Crash reports don't contain any personal information. To simply view the crash report without uploading it, you can click the green text.

Encrypting the paste such that we (hastebin server admins) can't see it is pointless, especially since all crash reports will automatically be pasted and reported to mod authors when snooper is enabled.
