### ISSUE TITLE
Crash when placing ProjectX2 Xyrconium Bricks

### ISSUE THREAD

**Issue by CvoidWyvern** [DimensionalDevelopment/VanillaFix#47]
VanillaFix version 1.0.6, started occurring at least on 1.0.4.  ProjectX2 on latest, but has had this issue with VanillaFix since 1.0.4.  

Anywhere the signature "noise" texture would be displayed is just clear.  This leads to some items being completely invisible.

**Comment by KitsuneAlex** [comment]
i recently talked to covers, the maintainer of chicken_bones' mods and he said that you need to add support for CCL and not vice-versa, if you show me where to add a animation update-method call i can fix it with a PR, also TiC and pretty much every other mod that adds fluids is kinda broken too

**Comment by Runemoro** [comment]
Yes, fluids are broken with Optifine, and fluids that aren't rendered in the world are broken too.

The animation is done here: https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/vanillafix/textures/mixins/client/MixinTextureMap.java#L35

References to other mods' classes can't be added to that class directly, though, since the Mixin will fail to load if that mod isn't loaded. Mod compatibility for chisel is done here: https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/vanillafix/textures/ModCompatibility.java#L29 

The animation code uses the texture lists from the visible CompiledChunks, and textures used on that tick for items, entities on fire, and all calls to the BlockModelRenderer/BlockFluidRenderer. For the liquids-in-tanks bug, there would have to be support for detecting visible liquids in a certain mod's tank.

**Comment by Runemoro** [comment]
@CvoidWyvern Everything is rendering properly for me... Which textures don't render exactly? Are you using Optifine?

**Comment by Runemoro** [comment]
The crash happens without VanillaFix too, as I described in https://github.com/KitsuneAlex/ProjectX/issues/8 (just place a xyrconium block and walk away from it). Everything else is rendering correctly with VanillaFix for me.
