### ISSUE TITLE
Config option to disable crash on scheduled tasks

### ISSUE THREAD

**Issue by Xiaminou** [DimensionalDevelopment/VanillaFix#7]
https://github.com/Tomson124/SimplyJetpacks-2/issues/82#issuecomment-386899736

Minecraft: 1.12.2
Forge: 2675
Mods: [list.txt](https://github.com/DimensionalDevelopment/VanillaFix/files/1977904/list.txt)

**Comment by Nianor** [comment]
I'm having the same issue. I can post my crash log if needed.

**Comment by ZombieHDGaming** [comment]
@Nianor Please do, it would help us even more.

**Comment by Runemoro** [comment]
Quoting my comment on the SimplyJetpacks issue:

> The issue is not caused by VanillaFix. The latest version of VanillaFix causes a crash when a scheduled task throws an exception as a feature to and inform the player that something went wrong rather than silently failing and possibly causing corruption or harder to debug errors later on, and to help mod makers with solving issues that might otherwise never be be found (without vanillafix, it only shows up as a log message).
>
>However, future versions will contain a config option to disable this feature (possibly even allowing resuming the game for all types of crashes)!

**Comment by Curunir** [comment]
Forgive me for asking, but this does not really make sense to me. Several users found that VanillaFix and Simply Jetpacks 2 together will cause modpacks to crash 100% on world load or join. Are you suggesting that VanillaFix works as intended, and SJ2 is just doing something unwise here? The scheduled crash option should not affect this, since the key combination to create one has not been triggered - or am I missing something here?

**Comment by ZombieHDGaming** [comment]
@Curunir VanillaFix is working as intended. I've had many mods put with VanillaFix and have never had an issue with scheduled tasks. If I had to guess based on the code I've seen in SJ2, the way Tomson handles configs may be causing the issue. Any other mod that does configs the proper way has shown no issues, but since Tomson seems to just have general methods for loading the various jetpacks and their tiers, this could be what's causing it. I'll do my own testing with the mods and see what happens, but I'm pretty safe in saying that this is not on our end.

**Comment by Runemoro** [comment]
Yes, the crash on scheduled task exceptions is a feature to avoid silent world corruption, and help mod makers fix their problems which they might otherwise not know about. Starting with next version, it will not kick you out to the main menu, but rather just show a warning screen.

**Comment by Curunir** [comment]
Thanks for the explanation, and thanks for your work.

**Comment by Runemoro** [comment]
Starting with next version, an error in a scheduled will only cause a warning screen rather than a crash screen by default (also configurable to "log only" and "crash").
