### ISSUE TITLE
Client doesn't start (possible incompatibility with malisis-core)

### ISSUE THREAD

**Issue by Bulldog83** [DimensionalDevelopment/VanillaFix#72]
Minecraft 1.12.2
Forge 14.23.4.2705
VanillaFix 1.0.8-88

This isn't a crash report, the game doesn't generate it, it just doesn't start.
https://gist.github.com/Bulldog83/e03ae25392624640fec3d1b7eedf830a

**Comment by Runemoro** [comment]
@Bulldog83 Can you include a full log?

**Comment by Bulldog83** [comment]
I've updated the log.

**Comment by Runemoro** [comment]
Are you sure that removing just VanillaFix fixes it? It looks like one of your other coremods loaded the `World` class before Minecraft started.

**Comment by Runemoro** [comment]
If you **remove** VanillaFix, does it still happen?

**Comment by Bulldog83** [comment]
Without VanillaFix, the client runs normally.

**Comment by Bulldog83** [comment]
I've found the mod that causing the problem. It's https://minecraft.curseforge.com/projects/time-speed-mod

**Comment by Runemoro** [comment]
Yes, I did some testing and confirmed that this is not caused by VanillaFix. You should report this to them, since it's not caused by VanillaFix, but only happens when VanillaFix is installed because the coremod loading order changed (and it would likely happen if you added any other coremods to your game).
