### ISSUE TITLE
Merge Texfix and Foamfix's tweaks to textures

### ISSUE THREAD

**Issue by JosEffigy** [DimensionalDevelopment/VanillaFix#86]
there might be a possiblity they use the same classes and negate each others optimizations with VanillaFix.  The creator of Foamfix is highly cooperative, dunno about Texfix

**Comment by Runemoro** [comment]
Neither of these mods replace whole classes, so they will work together without any problems. 

Foamfix's fixes won't be merged, but a feature is planned for VanillaFix later on to load resources (including textures) only as they are needed rather than when the game starts, which could reduce Minecraft's memory usage by a lot.

**Comment by Nordblum** [comment]
Wow, that sounds sick. Should be difficult as heck to implement though.

**Comment by Runemoro** [comment]
@Nordblum It has already been implemented in the latest dev builds, which you can find here: https://github.com/DimensionalDevelopment/VanillaFix/releases/latest

There are a few incompatibilities that need to be fixed before releasing on CurseForge though.
