### ISSUE TITLE
New OptiFine 1.12.2 HD U E1 conflict

### ISSUE THREAD

**Issue by JosEffigy** [DimensionalDevelopment/VanillaFix#89]
I think it's obvious why they conflict because optifine stole your idea and named it Smart Animations

**Comment by ZombieHDGaming** [comment]
I actually tried E1 with VF last night and had no issues from what I saw. What exactly is the conflict Optifine?

**Comment by JosEffigy** [comment]
Turning off all animations does not turn them off. Unless u disable
texturetweaks in the cfg
On Jun 27, 2018 7:22 PM, "Eion Dailey" <notifications@github.com> wrote:
>
> I actually tried E1 with VF last night and had no issues from what I saw.
What exactly is the conflict Optifine?

**Comment by Runemoro** [comment]
If you want to turn off all animations, then turn off the VF texture tweaks, and then turn off textures from Optifine. I'm surprised that the Optifine texture options even worked in previous versions, since VanillaFix completely overwrites the texture-related methods.

But why would you want to disable textures? VanillaFix's animated textures (and now Optifine's smart textures) are nearly as fast as having textures disabled completely, so you won't get any FPS increase by disabling them (though Optifine's smart textures don't have the support for other mods that VanillaFix does).

Support for Optifine won't be added. VanillaFix replaces Optifine's texture system so its texture options are expected to not work. An option to completely disable textures should instead be added to VanillaFix, but I don't see what the point of that would be.
